name: AureliumSkills
version: Alpha 1.3.0
main: com.archyx.aureliumskills.AureliumSkills
description: Feature-Packed Skills Plugin
author: Archyx
website: https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/
depend: [SmartInvs]
softdepend: [WorldGuard, PlaceholderAPI, HolographicDisplays]
api-version: 1.13

permissions:
    aureliumskills.skill.setlevel:
        default: op
    aureliumskills.ability.setlevel:
        default: op
    aureliumskils.reload:
        default: op
    aureliumskills.lang:
        default: op
    aureliumskills.xp.add:
        default: op
    aureliumskills.top:
        default: true
    aureliumskills.skill.reset:
        default: op