name: AureliumSkills
version: Alpha 1.1.2
main: io.github.archy_x.aureliumskills.AureliumSkills
description: Feature-Packed Skills Plugin
depend: [SmartInvs]
softdepend: [WorldGuard]
api-version: 1.13

permissions:
    aureliumskills.sp.add:
        default: op
    aureliumskills.skill.setlevel:
        default: op
    aureliumskills.ability.setlevel:
        default: op
    aureliumskils.reload:
        default: op
    aureliumskills.lang:
        default: op
    aureliumskills.xp.add:
        default: op
    aureliumskills.top:
        default: true