name: AureliumSkills
version: Alpha 1.4.1
main: com.archyx.aureliumskills.AureliumSkills
description: Feature-Packed Skills Plugin
author: Archyx
website: https://www.spigotmc.org/resources/aurelium-skills-advanced-skills-stats-abilities-and-more.81069/
softdepend: [WorldGuard, PlaceholderAPI, HolographicDisplays, Vault]
api-version: '1.13'

permissions:
    aureliumskills.*:
        description: Gives access to all Aurlium Skills commands
        children:
            aureliumskills.skill.setlevel: true
            aureliumskills.ability.setlevel: true
            aureliumskills.reload: true
            aureliumskills.lang: true
            aureliumskills.xp.add: true
            aureliumskills.top: true
            aureliumskills.skill.reset: true
            aureliumskills.xp.set: true
            aureliumskills.xp.remove: true
    aureliumskills.skill.setlevel:
        default: op
    aureliumskills.ability.setlevel:
        default: op
    aureliumskills.reload:
        default: op
    aureliumskills.lang:
        default: op
    aureliumskills.xp.add:
        default: op
    aureliumskills.xp.set:
        default: op
    aureliumskills.xp.remove:
        default: true
    aureliumskills.top:
        default: true
    aureliumskills.skill.reset:
        default: op
    aureliumskills.farming:
        default: true
    aureliumskills.foraging:
        default: true
    aureliumskills.mining:
        default: true
    aureliumskills.fishing:
        default: true
    aureliumskills.excavation:
        default: true
    aureliumskills.archery:
        default: true
    aureliumskills.defense:
        default: true
    aureliumskills.fighting:
        default: true
    aureliumskills.endurance:
        default: true
    aureliumskills.agility:
        default: true
    aureliumskills.alchemy:
        default: true
    aureliumskills.enchanting:
        default: true
    aureliumskills.sorcery:
        default: true
    aureliumskills.healing:
        default: true
    aureliumskills.forging:
        default: true