blank_issues_enabled: false
contact_links:
  - name: Aurelium Skills Diescord
    url: https://discord.gg/Bh2EZfB
    about: If you are trying to ask a question or have other issues with the plugin, please ask on our Discord server